[versions]
root = "2.0.14"
foundation = "1.5.3"
stdlib = "0.2.43"
tmp = "00.00.03"

[libraries]
applikation-runtime = { module = "tz.co.asoft:applikation-runtime", version.ref = "foundation" }

cache-api = { module = "tz.co.asoft:cache-api", version.ref = "root" }
cache-file = { module = "tz.co.asoft:cache-file", version.ref = "root" }
cache-browser = { module = "tz.co.asoft:cache-browser", version.ref = "root" }
cache-mock = { module = "tz.co.asoft:cache-mock", version.ref = "root" }
cache-react-native = { module = "tz.co.asoft:cache-react-native", version.ref = "root" }

kash-currency = { module = "tz.co.asoft:kash-currency", version.ref = "root" }
kash-money = { module = "tz.co.asoft:kash-money", version.ref = "root" }

kuest-core = { module = "tz.co.asoft:kuest-core", version.ref = "foundation" }
koncurrent-primitives-core = { module = "tz.co.asoft:koncurrent-primitives-core", version.ref = "root" }
koncurrent-primitives-coroutines = { module = "tz.co.asoft:koncurrent-primitives-coroutines", version.ref = "root" }
koncurrent-primitives-mock = { module = "tz.co.asoft:koncurrent-primitives-mock", version.ref = "root" }

koncurrent-later-core = { module = "tz.co.asoft:koncurrent-later-core", version.ref = "root" }
koncurrent-later-test = { module = "tz.co.asoft:koncurrent-later-test", version.ref = "root" }
koncurrent-later-coroutines = { module = "tz.co.asoft:koncurrent-later-coroutines", version.ref = "root" }

expect-core = { module = "tz.co.asoft:expect-core", version.ref = "root" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "root" }

identifier-core = { module = "tz.co.asoft:identifier-core", version.ref = "root" }
identifier-generators = { module = "tz.co.asoft:identifier-generators", version.ref = "root" }

kotlinx-collections-interoperable = { module = "tz.co.asoft:kotlinx-collections-interoperable", version.ref = "foundation" }
kotlinx-serialization-mapper = { module = "tz.co.asoft:kotlinx-serialization-mapper", version.ref = "foundation" }

platform-core = { module = "tz.co.asoft:platform-core", version.ref = "foundation" }

payments-requests-core = { module = "tz.co.asoft:payments-requests-core", version.ref = "stdlib" }

reakt-core = { module = "tz.co.asoft:reakt-core", version.ref = "stdlib" }
reakt-icons = { module = "tz.co.asoft:reakt-icons", version.ref = "stdlib" }
reakt-web = { module = "tz.co.asoft:reakt-web", version.ref = "stdlib" }

functions-core = { module = "tz.co.asoft:functions-core", version.ref = "root" }

kotlinx-browser = { module = "tz.co.asoft:kotlinx-browser", version.ref = "foundation" }
kotlinx-collections-atomic = { module = "tz.co.asoft:kotlinx-collections-atomic", version.ref = "foundation" }

live-core = { module = "tz.co.asoft:live-core", version.ref = "root" }
live-compose = { module = "tz.co.asoft:live-compose", version.ref = "root" }
live-coroutines = { module = "tz.co.asoft:live-coroutines", version.ref = "root" }
live-react = { module = "tz.co.asoft:live-react", version.ref = "root" }
live-test = { module = "tz.co.asoft:live-test", version.ref = "root" }

logging-console = { module = "tz.co.asoft:logging-console", version.ref = "foundation" }
logging-test-android = { module = "tz.co.asoft:logging-test-android", version.ref = "foundation" }

viewmodel-core = { module = "tz.co.asoft:viewmodel-core", version.ref = "root" }

foundation-plugins = { module = "tz.co.asoft:foundation-plugins", version.ref = "foundation" }

[plugins]
applikation = { id = "tz.co.asoft.applikation", version.ref = "foundation" }
library = { id = "tz.co.asoft.library", version.ref = "foundation" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "foundation" }